# Generated by Django 4.1.1 on 2022-10-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255)),
                ('content', models.FileField(upload_to='')),
                ('image', models.FileField(blank=True, upload_to='articles/media/images')),
                ('edit_date', models.DateField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['edit_date'],
            },
        ),
    ]
