# Generated by Django 4.1.2 on 2022-10-06 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e84c8c98-bf57-598f-b0b1-6e87dc2ee53a'), primary_key=True, serialize=False),
        ),
    ]
