# Generated by Django 4.1.2 on 2022-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_images_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='articles/media/images'),
        ),
    ]
