# Generated by Django 4.1.2 on 2022-10-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
    ]
